In [1]:
!pip install sentence_transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 KB 2.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 44.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 42.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.1/200.1 KB 14.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 38.8 MB/s eta 0:00:00
  Created wheel for sentence_transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125942 sha256=bc3984e8e485ce58ece46a88de7d49c83ea1b9770b3fc08ac4c5450e4b027019
  Stored in directory: /root/.cache/pip/wheels/71/67/06/162a3760c40d74dd40bc855d527008d26341c2b0ecf3e8e11f
Successfully built sentence_transformers


In [2]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [5]:
import torch
import numpy as np
from sentence_transformers import SentenceTransformer, util

In [6]:
model = SentenceTransformer('snunlp/KR-SBERT-V40K-klueNLI-augSTS')

## pytorch pt 모델로 저장

In [7]:
import torch

#torch.save(model, f'./model.pt')

In [8]:
device = "cuda" if torch.cuda.is_available() else "cpu"
LOAD_MODEL = torch.load("model.pt", map_location=device)

In [12]:
user_text = '내일 내 수업 목록좀 보여줘줘'

In [13]:
user_encode = LOAD_MODEL.encode(user_text)
user_tensor = torch.tensor(user_encode)

In [14]:
user_encode

array([ 1.11157462e-01, -3.37359041e-01,  9.68485922e-02,  8.54490638e-01,
       -3.62843066e-01, -1.03379034e-01, -1.78015884e-02,  7.35739842e-02,
        4.60803211e-01,  1.92838117e-01, -8.51951599e-01, -3.46374243e-01,
       -5.14692903e-01,  2.42286056e-01,  9.29478347e-01, -1.08673847e+00,
        5.17599225e-01, -4.39973295e-01,  8.08382869e-01,  9.70419109e-01,
        3.01087439e-01, -7.04666555e-01, -3.77122134e-01, -1.98437124e-01,
        1.61231965e-01, -1.61345482e+00, -1.72026023e-01, -2.90964395e-01,
       -9.54810530e-02,  6.31560504e-01,  8.88332188e-01,  7.98858941e-01,
        5.83339453e-01,  9.65856731e-01,  1.11531544e+00,  1.85575541e-02,
       -6.34628534e-01,  4.59246635e-02,  4.03391033e-01, -1.37910533e+00,
        4.68673408e-01,  4.16595221e-01,  1.78453147e-01,  6.49113804e-02,
       -2.51570195e-01,  3.43884498e-01,  4.71328557e-01,  1.52977216e+00,
        1.30422860e-02, -8.95075440e-01,  2.56534755e-01,  1.58994459e-02,
        1.23592162e+00, -

In [15]:
user_tensor

tensor([ 1.1116e-01, -3.3736e-01,  9.6849e-02,  8.5449e-01, -3.6284e-01,
        -1.0338e-01, -1.7802e-02,  7.3574e-02,  4.6080e-01,  1.9284e-01,
        -8.5195e-01, -3.4637e-01, -5.1469e-01,  2.4229e-01,  9.2948e-01,
        -1.0867e+00,  5.1760e-01, -4.3997e-01,  8.0838e-01,  9.7042e-01,
         3.0109e-01, -7.0467e-01, -3.7712e-01, -1.9844e-01,  1.6123e-01,
        -1.6135e+00, -1.7203e-01, -2.9096e-01, -9.5481e-02,  6.3156e-01,
         8.8833e-01,  7.9886e-01,  5.8334e-01,  9.6586e-01,  1.1153e+00,
         1.8558e-02, -6.3463e-01,  4.5925e-02,  4.0339e-01, -1.3791e+00,
         4.6867e-01,  4.1660e-01,  1.7845e-01,  6.4911e-02, -2.5157e-01,
         3.4388e-01,  4.7133e-01,  1.5298e+00,  1.3042e-02, -8.9508e-01,
         2.5653e-01,  1.5899e-02,  1.2359e+00, -7.6391e-01, -7.3300e-01,
        -5.2308e-01, -4.9433e-01, -8.6650e-01, -1.3075e+00, -1.1261e-01,
        -1.8023e-01,  9.1143e-01, -5.7397e-01, -8.3869e-01,  7.6347e-01,
         1.1445e+00,  6.5713e-01,  9.3825e-01,  1.2

In [16]:
print(LOAD_MODEL)

SentenceTransformer(
  (0): Transformer({'max_seq_length': 128, 'do_lower_case': False}) with Transformer model: BertModel 
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False})
)


# pickle 파일로 저장

In [17]:
import pickle

In [21]:
# def save_model(obj, filename):
#     with open(filename, 'wb') as f:
#         pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)

# save_model(model, 'model.pkl')

In [18]:
with open('model.pkl', 'rb') as f:
    LOAD_pickle_model = pickle.load(f)

user_encode2 = LOAD_pickle_model.encode(user_text)
user_tensor2 = torch.tensor(user_encode)

In [19]:
user_encode2

array([ 1.11157462e-01, -3.37359041e-01,  9.68485922e-02,  8.54490638e-01,
       -3.62843066e-01, -1.03379034e-01, -1.78015884e-02,  7.35739842e-02,
        4.60803211e-01,  1.92838117e-01, -8.51951599e-01, -3.46374243e-01,
       -5.14692903e-01,  2.42286056e-01,  9.29478347e-01, -1.08673847e+00,
        5.17599225e-01, -4.39973295e-01,  8.08382869e-01,  9.70419109e-01,
        3.01087439e-01, -7.04666555e-01, -3.77122134e-01, -1.98437124e-01,
        1.61231965e-01, -1.61345482e+00, -1.72026023e-01, -2.90964395e-01,
       -9.54810530e-02,  6.31560504e-01,  8.88332188e-01,  7.98858941e-01,
        5.83339453e-01,  9.65856731e-01,  1.11531544e+00,  1.85575541e-02,
       -6.34628534e-01,  4.59246635e-02,  4.03391033e-01, -1.37910533e+00,
        4.68673408e-01,  4.16595221e-01,  1.78453147e-01,  6.49113804e-02,
       -2.51570195e-01,  3.43884498e-01,  4.71328557e-01,  1.52977216e+00,
        1.30422860e-02, -8.95075440e-01,  2.56534755e-01,  1.58994459e-02,
        1.23592162e+00, -

In [20]:
user_tensor2

tensor([ 1.1116e-01, -3.3736e-01,  9.6849e-02,  8.5449e-01, -3.6284e-01,
        -1.0338e-01, -1.7802e-02,  7.3574e-02,  4.6080e-01,  1.9284e-01,
        -8.5195e-01, -3.4637e-01, -5.1469e-01,  2.4229e-01,  9.2948e-01,
        -1.0867e+00,  5.1760e-01, -4.3997e-01,  8.0838e-01,  9.7042e-01,
         3.0109e-01, -7.0467e-01, -3.7712e-01, -1.9844e-01,  1.6123e-01,
        -1.6135e+00, -1.7203e-01, -2.9096e-01, -9.5481e-02,  6.3156e-01,
         8.8833e-01,  7.9886e-01,  5.8334e-01,  9.6586e-01,  1.1153e+00,
         1.8558e-02, -6.3463e-01,  4.5925e-02,  4.0339e-01, -1.3791e+00,
         4.6867e-01,  4.1660e-01,  1.7845e-01,  6.4911e-02, -2.5157e-01,
         3.4388e-01,  4.7133e-01,  1.5298e+00,  1.3042e-02, -8.9508e-01,
         2.5653e-01,  1.5899e-02,  1.2359e+00, -7.6391e-01, -7.3300e-01,
        -5.2308e-01, -4.9433e-01, -8.6650e-01, -1.3075e+00, -1.1261e-01,
        -1.8023e-01,  9.1143e-01, -5.7397e-01, -8.3869e-01,  7.6347e-01,
         1.1445e+00,  6.5713e-01,  9.3825e-01,  1.2